// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9qYoOZO-zn0p2iIPQVtElBLssNuztX-k',
    appId: '1:239180640185:web:23cd8e66c0afd87afc5068',
    messagingSenderId: '239180640185',
    projectId: 'user-details-69172',
    authDomain: 'user-details-69172.firebaseapp.com',
    storageBucket: 'user-details-69172.firebasestorage.app',
    measurementId: 'G-8KJ7LT8132',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfUYQhbtCAJZSTj4lbAz8T5yGWCsQDS7s',
    appId: '1:239180640185:android:43189d0c91f882c9fc5068',
    messagingSenderId: '239180640185',
    projectId: 'user-details-69172',
    storageBucket: 'user-details-69172.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDmFPulzJMJgHssUmQPUJVUl59dsQyc7k',
    appId: '1:239180640185:ios:37c995c817a34f70fc5068',
    messagingSenderId: '239180640185',
    projectId: 'user-details-69172',
    storageBucket: 'user-details-69172.firebasestorage.app',
    iosBundleId: 'com.example.usersapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDmFPulzJMJgHssUmQPUJVUl59dsQyc7k',
    appId: '1:239180640185:ios:37c995c817a34f70fc5068',
    messagingSenderId: '239180640185',
    projectId: 'user-details-69172',
    storageBucket: 'user-details-69172.firebasestorage.app',
    iosBundleId: 'com.example.usersapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9qYoOZO-zn0p2iIPQVtElBLssNuztX-k',
    appId: '1:239180640185:web:8af4213402755e9efc5068',
    messagingSenderId: '239180640185',
    projectId: 'user-details-69172',
    authDomain: 'user-details-69172.firebaseapp.com',
    storageBucket: 'user-details-69172.firebasestorage.app',
    measurementId: 'G-RV2C09CGYZ',
  );
}
